# Generated by Django 5.2.5 on 2026-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_ticket_types',
            field=models.CharField(blank=True, help_text='Comma separated e.g., NEW,RENEWAL. Leave blank for ALL.', max_length=255),
        ),
    ]
