# Generated by Django 5.2.5 on 2026-03-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('NEW', 'New Policy'), ('RENEWAL', 'Renewal'), ('ADJUSTMENT', 'Adjustment'), ('CANCELLATION', 'Cancellation')], max_length=20)),
                ('status', models.CharField(choices=[('LEAD', 'Lead'), ('DOCS', 'Documents Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('DISCARDED', 'Discarded')], default='LEAD', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('insurance_type', models.CharField(max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WEB', 'Website'), ('MANUAL', 'Manual Entry')], default='MANUAL', max_length=20)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
