# Generated by Django 5.2.5 on 2026-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='details',
            field=models.TextField(),
        ),
    ]
